function init_routes()
{
	var route_list = {
		"1066.country.walk" : {
			"fullname"	: "1066 Country Walk",
			"name"		: "1066 Country Walk",
			"attr"		: "cehrst",
			"dist_route"	: 32,
			"date_start"	: "2013-01-09",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 31,
			"complete"	: 97,
			"latitude"	: 50.884842,
			"longitude"	: 0.521851,
			"zoom"		: 11,
			"custom"	: ""
		},
		"annandale.way" : {
			"fullname"	: "Annandale Way",
			"name"		: "Annandale Way",
			"attr"		: "ers",
			"dist_route"	: 53,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.160880,
			"longitude"	: -3.305511,
			"zoom"		: 10,
			"custom"	: ""
		},
		"arden.way" : {
			"fullname"	: "Arden Way",
			"name"		: "Arden Way",
			"attr"		: "cehrst",
			"dist_route"	: 27,
			"date_start"	: "2012-12-18",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 8,
			"complete"	: 30,
			"latitude"	: 52.264375,
			"longitude"	: -1.849136,
			"zoom"		: 12,
			"custom"	: ""
		},
		"ayrshire.coast" : {
			"fullname"	: "Ayrshire Coastal Path",
			"name"		: "Ayrshire Coast",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.463285,
			"longitude"	: -4.812012,
			"zoom"		: 8,
			"custom"	: ""
		},
		"berwick.boundary" : {
			"fullname"	: "Berwick Borough Boundary Walk",
			"name"		: "Berwick Boundary",
			"attr"		: "ers",
			"dist_route"	: 109,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.583002,
			"longitude"	: -2.024231,
			"zoom"		: 10,
			"custom"	: ""
		},
		"berwick.coast" : {
			"fullname"	: "Berwickshire Coastal Path",
			"name"		: "Berwick Coast",
			"attr"		: "ers",
			"dist_route"	: 29,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.866667,
			"longitude"	: -2.166667,
			"zoom"		: 11,
			"custom"	: ""
		},
		"calderdale.way" : {
			"fullname"	: "Calderdale Way",
			"name"		: "Calderdale Way",
			"attr"		: "ers",
			"dist_route"	: 50,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.723936,
			"longitude"	: -1.925354,
			"zoom"		: 11,
			"custom"	: ""
		},
		"central.scottish.way" : {
			"fullname"	: "Central Scottish Way",
			"name"		: "Central Scottish Way",
			"attr"		: "ers",
			"dist_route"	: 147,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.856817,
			"longitude"	: -3.142090,
			"zoom"		: 8,
			"custom"	: ""
		},
		"cleveland.way" : {
			"fullname"	: "Cleveland Way &mdash; National Trail",
			"name"		: "Cleveland Way",
			"attr"		: "cehrst",
			"dist_route"	: 106,
			"date_start"	: "2012-10-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 14,
			"complete"	: 13,
			"latitude"	: 54.404544,
			"longitude"	: -0.802002,
			"zoom"		: 10,
			"custom"	: ""
		},
		"coast.to.coast" : {
			"fullname"	: "Coast to Coast",
			"name"		: "Coast to Coast",
			"attr"		: "cehrs",
			"dist_route"	: 184,
			"date_start"	: "2012-09-28",
			"date_end"	: "2012-10-10",
			"days_walked"	: 13,
			"days_camped"	: 10,
			"days_other"	: 3,
			"dist_walked"	: 194,
			"complete"	: 100,
			"latitude"	: 54.425322,
			"longitude"	: -2.032471,
			"zoom"		: 8,
			"custom"	: ""
		},
		"coast.to.coast.alternative" : {
			"fullname"	: "Alternative Coast to Coast",
			"name"		: "Alternative Coast to Coast",
			"attr"		: "ers",
			"dist_route"	: 200,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.829172,
			"longitude"	: -2.433472,
			"zoom"		: 8,
			"custom"	: ""
		},
		"coast.to.coast.scotland" : {
			"fullname"	: "Coast to Coast Scotland",
			"name"		: "Coast to Coast Scotland",
			"attr"		: "ers",
			"dist_route"	: 134,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.398705,
			"longitude"	: -4.213257,
			"zoom"		: 8,
			"custom"	: ""
		},
		"coast.to.coast.south" : {
			"fullname"	: "Southern Coast to Coast",
			"name"		: "Southern Coast to Coast",
			"attr"		: "ers",
			"dist_route"	: 278,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.141448,
			"longitude"	: -1.142578,
			"zoom"		: 8,
			"custom"	: ""
		},
		"cotswold.canals" : {
			"fullname"	: "Cotswold Canals Walk",
			"name"		: "Cotswold Canals",
			"attr"		: "cehrst",
			"dist_route"	: 41,
			"date_start"	: "2013-02-28",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 23,
			"complete"	: 56,
			"latitude"	: 51.723626,
			"longitude"	: -2.028351,
			"zoom"		: 10,
			"custom"	: ""
		},
		"cotswold.diamond" : {
			"fullname"	: "Diamond Way North Cotswold",
			"name"		: "Cotswold Diamond",
			"attr"		: "ers",
			"dist_route"	: 65,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.940879,
			"longitude"	: -1.754379,
			"zoom"		: 11,
			"custom"	: ""
		},
		"cotswold.way" : {
			"fullname"	: "Cotswold Way &mdash; National Trail",
			"name"		: "Cotswold Way",
			"attr"		: "ers",
			"dist_route"	: 101,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.795027,
			"longitude"	: -2.153320,
			"zoom"		: 9,
			"custom"	: ""
		},
		"coventry.way" : {
			"fullname"	: "Coventry Way",
			"name"		: "Coventry Way",
			"attr"		: "ehrst",
			"dist_route"	: 40,
			"date_start"	: "2012-12-18",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 4,
			"complete"	: 10,
			"latitude"	: 52.409959,
			"longitude"	: -1.492081,
			"zoom"		: 11,
			"custom"	: ""
		},
		"cross.cotswold" : {
			"fullname"	: "Cross Cotswold Pathway",
			"name"		: "Cross Cotswold",
			"attr"		: "ers",
			"dist_route"	: 90,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.801822,
			"longitude"	: -1.881409,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbria.coast" : {
			"fullname"	: "Cumbria Coastal Way",
			"name"		: "Cumbria Coast",
			"attr"		: "ers",
			"dist_route"	: 192,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.535426,
			"longitude"	: -3.098145,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbria.way" : {
			"fullname"	: "Cumbria Way",
			"name"		: "Cumbria Way",
			"attr"		: "ers",
			"dist_route"	: 74,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.557730,
			"longitude"	: -3.081665,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbrian.trident" : {
			"fullname"	: "Cumbrian Classic Trident Walk",
			"name"		: "Cumbrian Trident",
			"attr"		: "ers",
			"dist_route"	: 97,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.509124,
			"longitude"	: -3.081665,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.centurion" : {
			"fullname"	: "Yorkshire Dales Centurion Walk",
			"name"		: "Dales Centurion",
			"attr"		: "cehrst",
			"dist_route"	: 100,
			"date_start"	: "2011-08-03",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 0,
			"days_other"	: 1,
			"dist_walked"	: 26,
			"complete"	: 26,
			"latitude"	: 54.308512,
			"longitude"	: -2.234344,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.challenge" : {
			"fullname"	: "Yorkshire Dales Challenge Walk",
			"name"		: "Dales Challenge",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.178713,
			"longitude"	: -2.117271,
			"zoom"		: 12,
			"custom"	: ""
		},
		"dales.top.ten" : {
			"fullname"	: "Yorkshire Dales Top Ten",
			"name"		: "Dales Top Ten",
			"attr"		: "cehrst",
			"dist_route"	: 77,
			"date_start"	: "2010-09-25",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 25,
			"complete"	: 32,
			"latitude"	: 54.265224,
			"longitude"	: -2.241211,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.walk" : {
			"fullname"	: "Dales Walk",
			"name"		: "Dales Walk",
			"attr"		: "cehrst",
			"dist_route"	: 72,
			"date_start"	: "2012-10-04",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 16,
			"complete"	: 22,
			"latitude"	: 54.372559,
			"longitude"	: -2.050323,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.way" : {
			"fullname"	: "Dales Way",
			"name"		: "Dales Way",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.191370,
			"longitude"	: -2.296143,
			"zoom"		: 9,
			"custom"	: ""
		},
		"dane.valley" : {
			"fullname"	: "Dane Valley Way",
			"name"		: "Dane Valley",
			"attr"		: "ers",
			"dist_route"	: 41,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.206033,
			"longitude"	: -2.142334,
			"zoom"		: 10,
			"custom"	: ""
		},
		"e2" : {
			"fullname"	: "E2 Dover to Stranraer",
			"name"		: "E2",
			"attr"		: "cehrstv",
			"dist_route"	: 874,
			"date_start"	: "2010-09-22",
			"date_end"	: "",
			"days_walked"	: 40,
			"days_camped"	: 33,
			"days_other"	: 4,
			"dist_walked"	: 721,
			"complete"	: 82,
			"latitude"	: 54.699234,
			"longitude"	: -4.943848,
			"zoom"		: 6,
			"custom"	: ""
		},
		"e8" : {
			"fullname"	: "E8 Hull to Liverpool",
			"name"		: "E8",
			"attr"		: "ers",
			"dist_route"	: 179,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.497850,
			"longitude"	: -1.642456,
			"zoom"		: 8,
			"custom"	: ""
		},
		"e9" : {
			"fullname"	: "E9 Dover to Plymouth",
			"name"		: "E9",
			"attr"		: "cefhrsv",
			"dist_route"	: 440,
			"date_start"	: "2012-06-13",
			"date_end"	: "2013-01-12",
			"days_walked"	: 24,
			"days_camped"	: 18,
			"days_other"	: 4,
			"dist_walked"	: 464,
			"complete"	: 100,
			"latitude"	: 50.590212,
			"longitude"	: -1.450195,
			"zoom"		: 7,
			"custom"	: ""
		},
		"elham.valley" : {
			"fullname"	: "Elham Valley Way",
			"name"		: "Elham Valley",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.184938,
			"longitude"	: 1.119232,
			"zoom"		: 11,
			"custom"	: ""
		},
		"esk.valley" : {
			"fullname"	: "Esk Valley Walk",
			"name"		: "Esk Valley",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.428518,
			"longitude"	: -0.790329,
			"zoom"		: 11,
			"custom"	: ""
		},
		"eskdale.way" : {
			"fullname"	: "Eskdale Way",
			"name"		: "Eskdale Way",
			"attr"		: "ers",
			"dist_route"	: 88,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.434908,
			"longitude"	: -0.843201,
			"zoom"		: 11,
			"custom"	: ""
		},
		"etherow.goyt.valley" : {
			"fullname"	: "Etherow &mdash; Goyt Valley Way",
			"name"		: "Etherow &mdash; Goyt Valley",
			"attr"		: "ers",
			"dist_route"	: 14,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.428560,
			"longitude"	: -2.040367,
			"zoom"		: 12,
			"custom"	: ""
		},
		"fife.coast" : {
			"fullname"	: "Fife Coastal Path",
			"name"		: "Fife Coast",
			"attr"		: "ers",
			"dist_route"	: 115,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.238008,
			"longitude"	: -3.228607,
			"zoom"		: 10,
			"custom"	: ""
		},
		"five.degrees.west" : {
			"fullname"	: "Five Degrees West Challenge",
			"name"		: "Five Degrees West",
			"attr"		: "cehrstx",
			"dist_route"	: 290,
			"date_start"	: "2013-06-10",
			"date_end"	: "",
			"days_walked"	: 8,
			"days_camped"	: 8,
			"days_other"	: 0,
			"dist_walked"	: 120,
			"complete"	: 40,
			"latitude"	: 57.106419,
			"longitude"	: -4.943848,
			"zoom"		: 7,
			"custom"	: "line,crossovers"
		},
		"gloucestershire.way" : {
			"fullname"	: "Gloucestershire Way",
			"name"		: "Gloucestershire Way",
			"attr"		: "ers",
			"dist_route"	: 94,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.808615,
			"longitude"	: -2.230225,
			"zoom"		: 10,
			"custom"	: ""
		},
		"glyndwrs.way" : {
			"fullname"	: "Glyndwr's Way &mdash; National Trail",
			"name"		: "Glyndwr's Way",
			"attr"		: "ers",
			"dist_route"	: 137,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.538779,
			"longitude"	: -3.361816,
			"zoom"		: 10,
			"custom"	: ""
		},
		"goyt.way" : {
			"fullname"	: "Goyt Way",
			"name"		: "Goyt Way",
			"attr"		: "ers",
			"dist_route"	: 10,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.371654,
			"longitude"	: -2.028351,
			"zoom"		: 12,
			"custom"	: ""
		},
		"great.english.walk" : {
			"fullname"	: "Great English Walk",
			"name"		: "Great English Walk",
			"attr"		: "ers",
			"dist_route"	: 586,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.638125,
			"longitude"	: -2.065430,
			"zoom"		: 7,
			"custom"	: ""
		},
		"great.glen.way" : {
			"fullname"	: "Great Glen Way &mdash; National Trail",
			"name"		: "Great Glen Way",
			"attr"		: "ers",
			"dist_route"	: 73,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.166036,
			"longitude"	: -4.600525,
			"zoom"		: 9,
			"custom"	: ""
		},
		"gritstone.trail" : {
			"fullname"	: "Gritstone Trail",
			"name"		: "Gritstone Trail",
			"attr"		: "cehrst",
			"dist_route"	: 35,
			"date_start"	: "2012-12-12",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 21,
			"complete"	: 60,
			"latitude"	: 53.217546,
			"longitude"	: -2.140961,
			"zoom"		: 10,
			"custom"	: ""
		},
		"hadrians.coast" : {
			"fullname"	: "Hadrian's Coastal Route",
			"name"		: "Hadrian's Coast",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.678595,
			"longitude"	: -3.370056,
			"zoom"		: 9,
			"custom"	: ""
		},
		"hadrians.wall" : {
			"fullname"	: "Hadrian's Wall Path &mdash; National Trail",
			"name"		: "Hadrian's Wall",
			"attr"		: "ehrst",
			"dist_route"	: 86,
			"date_start"	: "2012-10-14",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 9,
			"complete"	: 10,
			"latitude"	: 54.963425,
			"longitude"	: -2.364807,
			"zoom"		: 9,
			"custom"	: ""
		},
		"heart.of.england" : {
			"fullname"	: "Heart of England Way",
			"name"		: "Heart of England",
			"attr"		: "cehrst",
			"dist_route"	: 101,
			"date_start"	: "2012-12-16",
			"date_end"	: "",
			"days_walked"	: 6,
			"days_camped"	: 5,
			"days_other"	: 0,
			"dist_walked"	: 103,
			"complete"	: 95,
			"latitude"	: 52.357151,
			"longitude"	: -1.845703,
			"zoom"		: 9,
			"custom"	: ""
		},
		"heart.of.snowdonia" : {
			"fullname"	: "Heart of Snowdonia",
			"name"		: "Heart of Snowdonia",
			"attr"		: "ers",
			"dist_route"	: 49,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.081240,
			"longitude"	: -4.011383,
			"zoom"		: 11,
			"custom"	: ""
		},
		"hobblers.way" : {
			"fullname"	: "Hobblers Way",
			"name"		: "Hobblers Way",
			"attr"		: "ers",
			"dist_route"	: 192,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.221070,
			"longitude"	: -1.071167,
			"zoom"		: 8,
			"custom"	: ""
		},
		"isaacs.tea.trail" : {
			"fullname"	: "Isaac's Tea Trail",
			"name"		: "Isaac's Tea Trail",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.849932,
			"longitude"	: -2.347641,
			"zoom"		: 12,
			"custom"	: ""
		},
		"isle.of.wight.coast" : {
			"fullname"	: "Isle of Wight Coastal Path",
			"name"		: "Isle of Wight Coast",
			"attr"		: "cehrs",
			"dist_route"	: 69,
			"date_start"	: "2012-12-30",
			"date_end"	: "2013-01-02",
			"days_walked"	: 3,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 70,
			"complete"	: 100,
			"latitude"	: 50.670789,
			"longitude"	: -1.321793,
			"zoom"		: 11,
			"custom"	: ""
		},
		"itchen.way" : {
			"fullname"	: "Itchen Way",
			"name"		: "Itchen Way",
			"attr"		: "ers",
			"dist_route"	: 30,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.984370,
			"longitude"	: -1.290207,
			"zoom"		: 11,
			"custom"	: ""
		},
		"join.1" : {
			"fullname"	: "Bridgwater to Avonmouth",
			"name"		: "Bridgwater to Avonmouth",
			"attr"		: "cehs",
			"dist_route"	: 61,
			"date_start"	: "2013-05-01",
			"date_end"	: "2013-05-04",
			"days_walked"	: 4,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 61,
			"complete"	: 100,
			"latitude"	: 51.346054,
			"longitude"	: -2.923737,
			"zoom"		: 10,
			"custom"	: ""
		},
		"join.2" : {
			"fullname"	: "Aust to Chepstow",
			"name"		: "Aust to Chepstow",
			"attr"		: "ehs",
			"dist_route"	: 5,
			"date_start"	: "2013-05-07",
			"date_end"	: "2013-05-07",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 5,
			"complete"	: 100,
			"latitude"	: 51.621747,
			"longitude"	: -2.654057,
			"zoom"		: 13,
			"custom"	: ""
		},
		"join.3" : {
			"fullname"	: "Gourock to Toward Point",
			"name"		: "Gourock to Toward Point",
			"attr"		: "efhs",
			"dist_route"	: 7,
			"date_start"	: "2013-06-10",
			"date_end"	: "2013-06-10",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 100,
			"latitude"	: 55.899186,
			"longitude"	: -4.889603,
			"zoom"		: 11,
			"custom"	: ""
		},
		"kent.coast" : {
			"fullname"	: "Kent Coast Path",
			"name"		: "Kent Coast",
			"attr"		: "cehrsv",
			"dist_route"	: 207,
			"date_start"	: "2013-01-11",
			"date_end"	: "2013-01-21",
			"days_walked"	: 10,
			"days_camped"	: 8,
			"days_other"	: 1,
			"dist_walked"	: 211,
			"complete"	: 100,
			"latitude"	: 51.198279,
			"longitude"	: 0.832214,
			"zoom"		: 9,
			"custom"	: ""
		},
		"lancashire.coast" : {
			"fullname"	: "Lancashire Coastal Way",
			"name"		: "Lancashire Coast",
			"attr"		: "ers",
			"dist_route"	: 68,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.956086,
			"longitude"	: -2.860565,
			"zoom"		: 10,
			"custom"	: ""
		},
		"lyke.wake.walk" : {
			"fullname"	: "Lyke Wake Walk",
			"name"		: "Lyke Wake Walk",
			"attr"		: "cehrst",
			"dist_route"	: 39,
			"date_start"	: "2012-10-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 22,
			"complete"	: 56,
			"latitude"	: 54.398149,
			"longitude"	: -0.892639,
			"zoom"		: 10,
			"custom"	: ""
		},
		"macmillan.abbotsbury.langport" : {
			"fullname"	: "Macmillan Abbotsbury Langport Link",
			"name"		: "Macmillan Abbotsbury Langport",
			"attr"		: "ers",
			"dist_route"	: 40,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.875311,
			"longitude"	: -2.712250,
			"zoom"		: 10,
			"custom"	: ""
		},
		"macmillan.way" : {
			"fullname"	: "Macmillan Way",
			"name"		: "Macmillan Way",
			"attr"		: "ers",
			"dist_route"	: 287,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.099757,
			"longitude"	: -1.065674,
			"zoom"		: 7,
			"custom"	: ""
		},
		"macmillan.way.west" : {
			"fullname"	: "Macmillan Way West",
			"name"		: "Macmillan Way West",
			"attr"		: "ers",
			"dist_route"	: 102,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.110420,
			"longitude"	: -3.342590,
			"zoom"		: 9,
			"custom"	: ""
		},
		"midshires.way" : {
			"fullname"	: "Midshires Way",
			"name"		: "Midshires Way",
			"attr"		: "ers",
			"dist_route"	: 224,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.636397,
			"longitude"	: -1.334839,
			"zoom"		: 8,
			"custom"	: ""
		},
		"millennium.way" : {
			"fullname"	: "Way For The Millennium",
			"name"		: "Millennium Way",
			"attr"		: "ers",
			"dist_route"	: 38,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.762892,
			"longitude"	: -1.972046,
			"zoom"		: 10,
			"custom"	: ""
		},
		"monarchs.way" : {
			"fullname"	: "Monarch's Way",
			"name"		: "Monarch's Way",
			"attr"		: "ers",
			"dist_route"	: 565,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.655519,
			"longitude"	: -2.147827,
			"zoom"		: 8,
			"custom"	: ""
		},
		"mull.of.galloway.trail" : {
			"fullname"	: "Mull of Galloway Trail",
			"name"		: "Mull of Galloway Trail",
			"attr"		: "ers",
			"dist_route"	: 36,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.846571,
			"longitude"	: -4.980927,
			"zoom"		: 10,
			"custom"	: ""
		},
		"munros" : {
			"fullname"	: "Munros &mdash; Scotland",
			"name"		: "Munros",
			"attr"		: "ap",
			"dist_route"	: 0,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.670616,
			"longitude"	: -4.224243,
			"zoom"		: 7,
			"custom"	: ""
		},
		"nelson.way" : {
			"fullname"	: "Nelson Way",
			"name"		: "Nelson Way",
			"attr"		: "ers",
			"dist_route"	: 406,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.730431,
			"longitude"	: 0.318604,
			"zoom"		: 8,
			"custom"	: ""
		},
		"north.downs" : {
			"fullname"	: "North Downs Way &mdash; National Trail",
			"name"		: "North Downs",
			"attr"		: "cehrsv",
			"dist_route"	: 125,
			"date_start"	: "2013-01-12",
			"date_end"	: "2013-02-08",
			"days_walked"	: 7,
			"days_camped"	: 5,
			"days_other"	: 1,
			"dist_walked"	: 132,
			"complete"	: 100,
			"latitude"	: 51.063839,
			"longitude"	: 0.285645,
			"zoom"		: 9,
			"custom"	: ""
		},
		"north.to.the.cape" : {
			"fullname"	: "North to the Cape",
			"name"		: "North to the Cape",
			"attr"		: "ers",
			"dist_route"	: 218,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.671848,
			"longitude"	: -5.026245,
			"zoom"		: 8,
			"custom"	: ""
		},
		"northumberland.coast" : {
			"fullname"	: "Northumberland Coast Path",
			"name"		: "Northumberland Coast",
			"attr"		: "ers",
			"dist_route"	: 64,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.522412,
			"longitude"	: -1.782532,
			"zoom"		: 9,
			"custom"	: ""
		},
		"offas.dyke" : {
			"fullname"	: "Offa's Dyke Path &mdash; National Trail",
			"name"		: "Offa's Dyke",
			"attr"		: "cehrs",
			"dist_route"	: 178,
			"date_start"	: "2013-05-07",
			"date_end"	: "2013-05-16",
			"days_walked"	: 9,
			"days_camped"	: 10,
			"days_other"	: 0,
			"dist_walked"	: 180,
			"complete"	: 100,
			"latitude"	: 52.479435,
			"longitude"	: -3.246460,
			"zoom"		: 8,
			"custom"	: ""
		},
		"oldham.way" : {
			"fullname"	: "Oldham Way",
			"name"		: "Oldham Way",
			"attr"		: "cehrst",
			"dist_route"	: 39,
			"date_start"	: "2010-09-22",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 12,
			"complete"	: 31,
			"latitude"	: 53.544184,
			"longitude"	: -2.065086,
			"zoom"		: 12,
			"custom"	: ""
		},
		"oxford.canal" : {
			"fullname"	: "Oxford Canal Walk",
			"name"		: "Oxford Canal",
			"attr"		: "cehrst",
			"dist_route"	: 82,
			"date_start"	: "2013-02-23",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 11,
			"complete"	: 13,
			"latitude"	: 52.104818,
			"longitude"	: -0.997009,
			"zoom"		: 9,
			"custom"	: ""
		},
		"oxford.green.belt" : {
			"fullname"	: "Oxford Green Belt Way",
			"name"		: "Oxford Green Belt",
			"attr"		: "cehrs",
			"dist_route"	: 52,
			"date_start"	: "2013-02-24",
			"date_end"	: "2013-03-07",
			"days_walked"	: 4,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 57,
			"complete"	: 100,
			"latitude"	: 51.743612,
			"longitude"	: -1.208496,
			"zoom"		: 11,
			"custom"	: ""
		},
		"oxfordshire.way" : {
			"fullname"	: "Oxfordshire Way",
			"name"		: "Oxfordshire Way",
			"attr"		: "cehrst",
			"dist_route"	: 67,
			"date_start"	: "2012-12-21",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 30,
			"complete"	: 45,
			"latitude"	: 51.720223,
			"longitude"	: -1.332092,
			"zoom"		: 10,
			"custom"	: ""
		},
		"peddars.way.and.norfolk.coast" : {
			"fullname"	: "Peddars Way and Norfolk Coast Path &mdash; National Trail",
			"name"		: "Peddars Way and Norfolk Coast",
			"attr"		: "ers",
			"dist_route"	: 97,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.757905,
			"longitude"	: 0.892639,
			"zoom"		: 9,
			"custom"	: ""
		},
		"pembrokeshire.coast" : {
			"fullname"	: "Pembrokeshire Coast Path &mdash; National Trail",
			"name"		: "Pembrokeshire Coast",
			"attr"		: "ers",
			"dist_route"	: 182,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.849353,
			"longitude"	: -4.879303,
			"zoom"		: 10,
			"custom"	: ""
		},
		"pennine.bridleway" : {
			"fullname"	: "Pennine Bridleway &mdash; National Trail",
			"name"		: "Pennine Bridleway",
			"attr"		: "ers",
			"dist_route"	: 163,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.690201,
			"longitude"	: -2.164307,
			"zoom"		: 8,
			"custom"	: ""
		},
		"pennine.way" : {
			"fullname"	: "Pennine Way &mdash; National Trail",
			"name"		: "Pennine Way",
			"attr"		: "cehrs",
			"dist_route"	: 255,
			"date_start"	: "2010-09-20",
			"date_end"	: "2012-10-18",
			"days_walked"	: 16,
			"days_camped"	: 14,
			"days_other"	: 3,
			"dist_walked"	: 269,
			"complete"	: 100,
			"latitude"	: 53.994854,
			"longitude"	: -0.769043,
			"zoom"		: 7,
			"custom"	: ""
		},
		"pilgrims.way" : {
			"fullname"	: "Pilgrim's Way",
			"name"		: "Pilgrim's Way",
			"attr"		: "cehrst",
			"dist_route"	: 132,
			"date_start"	: "2013-02-04",
			"date_end"	: "",
			"days_walked"	: 5,
			"days_camped"	: 4,
			"days_other"	: 0,
			"dist_walked"	: 106,
			"complete"	: 80,
			"latitude"	: 51.025849,
			"longitude"	: -0.131836,
			"zoom"		: 9,
			"custom"	: ""
		},
		"ribble.way" : {
			"fullname"	: "Ribble Way",
			"name"		: "Ribble Way",
			"attr"		: "ers",
			"dist_route"	: 69,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.964165,
			"longitude"	: -2.419739,
			"zoom"		: 9,
			"custom"	: ""
		},
		"ridgeway" : {
			"fullname"	: "Ridgeway &mdash; National Trail",
			"name"		: "Ridgeway",
			"attr"		: "ers",
			"dist_route"	: 86,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.614606,
			"longitude"	: -1.186523,
			"zoom"		: 10,
			"custom"	: ""
		},
		"river.parrett" : {
			"fullname"	: "River Parrett Trail",
			"name"		: "River Parrett",
			"attr"		: "cehrst",
			"dist_route"	: 44,
			"date_start"	: "2013-04-30",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 12,
			"complete"	: 27,
			"latitude"	: 51.024121,
			"longitude"	: -2.855072,
			"zoom"		: 10,
			"custom"	: ""
		},
		"rob.roy.way" : {
			"fullname"	: "Rob Roy Way",
			"name"		: "Rob Roy Way",
			"attr"		: "ers",
			"dist_route"	: 79,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.409343,
			"longitude"	: -4.095154,
			"zoom"		: 9,
			"custom"	: ""
		},
		"rochdale.way" : {
			"fullname"	: "Rochdale Way",
			"name"		: "Rochdale Way",
			"attr"		: "ers",
			"dist_route"	: 48,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.613081,
			"longitude"	: -2.146454,
			"zoom"		: 12,
			"custom"	: ""
		},
		"saxon.shore" : {
			"fullname"	: "Saxon Shore Way",
			"name"		: "Saxon Shore",
			"attr"		: "cehrst",
			"dist_route"	: 163,
			"date_start"	: "2013-01-12",
			"date_end"	: "",
			"days_walked"	: 9,
			"days_camped"	: 5,
			"days_other"	: 1,
			"dist_walked"	: 104,
			"complete"	: 64,
			"latitude"	: 51.169011,
			"longitude"	: 0.818481,
			"zoom"		: 9,
			"custom"	: ""
		},
		"sefton.coast" : {
			"fullname"	: "Sefton Coastal Path",
			"name"		: "Sefton Coast",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.581500,
			"longitude"	: -3.019867,
			"zoom"		: 11,
			"custom"	: ""
		},
		"severn.way" : {
			"fullname"	: "Severn Way",
			"name"		: "Severn Way",
			"attr"		: "cehrst",
			"dist_route"	: 224,
			"date_start"	: "2013-05-04",
			"date_end"	: "",
			"days_walked"	: 4,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 41,
			"complete"	: 18,
			"latitude"	: 52.146973,
			"longitude"	: -2.982788,
			"zoom"		: 8,
			"custom"	: ""
		},
		"shakespeares.way" : {
			"fullname"	: "Shakespeare's Way",
			"name"		: "Shakespeare's Way",
			"attr"		: "ers",
			"dist_route"	: 129,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.779736,
			"longitude"	: -1.197510,
			"zoom"		: 9,
			"custom"	: ""
		},
		"snowdon.horseshoe" : {
			"fullname"	: "Snowdon Horseshoe",
			"name"		: "Snowdon Horseshoe",
			"attr"		: "ehrs",
			"dist_route"	: 7,
			"date_start"	: "2005-08-20",
			"date_end"	: "2005-08-20",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 100,
			"latitude"	: 53.069174,
			"longitude"	: -4.050007,
			"zoom"		: 14,
			"custom"	: ""
		},
		"snowdonia.to.the.gower" : {
			"fullname"	: "Snowdonia to the Gower",
			"name"		: "Snowdonia to the Gower",
			"attr"		: "ers",
			"dist_route"	: 209,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.425873,
			"longitude"	: -3.850708,
			"zoom"		: 8,
			"custom"	: ""
		},
		"solent.way" : {
			"fullname"	: "Solent Way",
			"name"		: "Solent Way",
			"attr"		: "cehrst",
			"dist_route"	: 63,
			"date_start"	: "2012-12-30",
			"date_end"	: "",
			"days_walked"	: 5,
			"days_camped"	: 3,
			"days_other"	: 1,
			"dist_walked"	: 58,
			"complete"	: 92,
			"latitude"	: 50.739932,
			"longitude"	: -1.196136,
			"zoom"		: 10,
			"custom"	: ""
		},
		"south.downs" : {
			"fullname"	: "South Downs Way &mdash; National Trail",
			"name"		: "South Downs",
			"attr"		: "cehrst",
			"dist_route"	: 95,
			"date_start"	: "2013-01-06",
			"date_end"	: "",
			"days_walked"	: 4,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 74,
			"complete"	: 78,
			"latitude"	: 50.786838,
			"longitude"	: -0.359802,
			"zoom"		: 9,
			"custom"	: ""
		},
		"south.tyne.trail" : {
			"fullname"	: "South Tyne Trail",
			"name"		: "South Tyne Trail",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.844199,
			"longitude"	: -2.462311,
			"zoom"		: 11,
			"custom"	: ""
		},
		"south.west.coast" : {
			"fullname"	: "South West Coast Path &mdash; National Trail",
			"name"		: "South West Coast",
			"attr"		: "cefhrsx",
			"dist_route"	: 630,
			"date_start"	: "2012-04-30",
			"date_end"	: "2012-06-23",
			"days_walked"	: 36,
			"days_camped"	: 32,
			"days_other"	: 3,
			"dist_walked"	: 648,
			"complete"	: 100,
			"latitude"	: 50.457504,
			"longitude"	: -4.037476,
			"zoom"		: 8,
			"custom"	: "ferry_icon"
		},
		"southern.upland.way" : {
			"fullname"	: "Southern Upland Way &mdash; National Trail",
			"name"		: "Southern Upland Way",
			"attr"		: "ers",
			"dist_route"	: 211,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.394712,
			"longitude"	: -3.543091,
			"zoom"		: 8,
			"custom"	: ""
		},
		"speyside.way" : {
			"fullname"	: "Speyside Way &mdash; National Trail",
			"name"		: "Speyside Way",
			"attr"		: "ers",
			"dist_route"	: 66,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.405023,
			"longitude"	: -3.337097,
			"zoom"		: 10,
			"custom"	: ""
		},
		"st.cuthberts" : {
			"fullname"	: "St Cuthbert's Way",
			"name"		: "St Cuthbert's Way",
			"attr"		: "ers",
			"dist_route"	: 64,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.550388,
			"longitude"	: -2.254944,
			"zoom"		: 10,
			"custom"	: ""
		},
		"staffordshire.gritstone" : {
			"fullname"	: "Staffordshire Gritstone Walk",
			"name"		: "Staffordshire Gritstone",
			"attr"		: "ers",
			"dist_route"	: 35,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.158300,
			"longitude"	: -1.947670,
			"zoom"		: 12,
			"custom"	: ""
		},
		"staffordshire.moorlands" : {
			"fullname"	: "Staffordshire Moorlands Challenge Walk",
			"name"		: "Staffordshire Moorlands",
			"attr"		: "ehrst",
			"dist_route"	: 22,
			"date_start"	: "2012-12-14",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 5,
			"complete"	: 23,
			"latitude"	: 53.000736,
			"longitude"	: -1.883125,
			"zoom"		: 12,
			"custom"	: ""
		},
		"staffordshire.way" : {
			"fullname"	: "Staffordshire Way",
			"name"		: "Staffordshire Way",
			"attr"		: "cehrst",
			"dist_route"	: 95,
			"date_start"	: "2012-12-13",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 47,
			"complete"	: 49,
			"latitude"	: 52.792797,
			"longitude"	: -2.046204,
			"zoom"		: 9,
			"custom"	: ""
		},
		"standedge.trail" : {
			"fullname"	: "Standedge Trail",
			"name"		: "Standedge Trail",
			"attr"		: "ers",
			"dist_route"	: 11,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.585882,
			"longitude"	: -1.959686,
			"zoom"		: 13,
			"custom"	: ""
		},
		"staunton.way" : {
			"fullname"	: "Staunton Way",
			"name"		: "Staunton Way",
			"attr"		: "ers",
			"dist_route"	: 21,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.927925,
			"longitude"	: -0.952377,
			"zoom"		: 12,
			"custom"	: ""
		},
		"suffolk.coast.and.heath" : {
			"fullname"	: "Suffolk Coast and Heath Path",
			"name"		: "Suffolk Coast and Heath",
			"attr"		: "ers",
			"dist_route"	: 58,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.209290,
			"longitude"	: 1.610870,
			"zoom"		: 10,
			"custom"	: ""
		},
		"tameside.trail" : {
			"fullname"	: "Tameside Trail",
			"name"		: "Tameside Trail",
			"attr"		: "ehrst",
			"dist_route"	: 34,
			"date_start"	: "2012-12-11",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 10,
			"complete"	: 29,
			"latitude"	: 53.478852,
			"longitude"	: -2.075386,
			"zoom"		: 12,
			"custom"	: ""
		},
		"tandridge.border" : {
			"fullname"	: "Tandridge Border Path",
			"name"		: "Tandridge Border",
			"attr"		: "ers",
			"dist_route"	: 52,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.231828,
			"longitude"	: -0.045319,
			"zoom"		: 11,
			"custom"	: ""
		},
		"tennyson.trail" : {
			"fullname"	: "Tennyson Trail",
			"name"		: "Tennyson Trail",
			"attr"		: "ers",
			"dist_route"	: 14,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.662955,
			"longitude"	: -1.428909,
			"zoom"		: 11,
			"custom"	: ""
		},
		"thames.estuary" : {
			"fullname"	: "Thames Estuary Trail",
			"name"		: "Thames Estuary",
			"attr"		: "ers",
			"dist_route"	: 115,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.480528,
			"longitude"	: 0.623474,
			"zoom"		: 10,
			"custom"	: ""
		},
		"thames.path" : {
			"fullname"	: "Thames Path &mdash; National Trail",
			"name"		: "Thames Path",
			"attr"		: "cehrstv",
			"dist_route"	: 182,
			"date_start"	: "2013-02-19",
			"date_end"	: "",
			"days_walked"	: 8,
			"days_camped"	: 6,
			"days_other"	: 0,
			"dist_walked"	: 166,
			"complete"	: 91,
			"latitude"	: 51.536086,
			"longitude"	: -0.999756,
			"zoom"		: 9,
			"custom"	: ""
		},
		"thanet.coast" : {
			"fullname"	: "Thanet Coastal Path",
			"name"		: "Thanet Coast",
			"attr"		: "cehrs",
			"dist_route"	: 20,
			"date_start"	: "2013-01-14",
			"date_end"	: "2013-01-15",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 21,
			"complete"	: 100,
			"latitude"	: 51.352058,
			"longitude"	: 1.332092,
			"zoom"		: 12,
			"custom"	: ""
		},
		"three.ridings" : {
			"fullname"	: "Three Ridings on Foot",
			"name"		: "Three Ridings",
			"attr"		: "ers",
			"dist_route"	: 444,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.985165,
			"longitude"	: -1.312866,
			"zoom"		: 8,
			"custom"	: ""
		},
		"three.towers" : {
			"fullname"	: "Three Towers",
			"name"		: "Three Towers",
			"attr"		: "ehrsx",
			"dist_route"	: 45,
			"date_start"	: "2010-04-10",
			"date_end"	: "2010-04-10",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 45,
			"complete"	: 100,
			"latitude"	: 51.510025,
			"longitude"	: -1.198196,
			"zoom"		: 11,
			"custom"	: "checkpoints"
		},
		"todmorden.centenary" : {
			"fullname"	: "Todmorden Centenary Way",
			"name"		: "Todmorden Centenary",
			"attr"		: "ers",
			"dist_route"	: 24,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.705853,
			"longitude"	: -2.097702,
			"zoom"		: 13,
			"custom"	: ""
		},
		"trans.pennine" : {
			"fullname"	: "Trans-Pennine Trail",
			"name"		: "Trans-Pennine",
			"attr"		: "ers",
			"dist_route"	: 209,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.589244,
			"longitude"	: -1.609497,
			"zoom"		: 8,
			"custom"	: ""
		},
		"tyne.estuary" : {
			"fullname"	: "Tyne Estuary to Source",
			"name"		: "Tyne Estuary",
			"attr"		: "ers",
			"dist_route"	: 87,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.901093,
			"longitude"	: -1.937714,
			"zoom"		: 10,
			"custom"	: ""
		},
		"wainwrights" : {
			"fullname"	: "Wainwrights &mdash; Lake District",
			"name"		: "Wainwrights",
			"attr"		: "AawchPps",
			"dist_route"	: 0,
			"date_start"	: "2012-10-22",
			"date_end"	: "",
			"days_walked"	: 7,
			"days_camped"	: 6,
			"days_other"	: 1,
			"dist_walked"	: 104,
			"complete"	: 11,
			"latitude"	: 54.484200,
			"longitude"	: -3.079490,
			"zoom"		: 10,
			"custom"	: ""
		},
		"wales.coast" : {
			"fullname"	: "Wales Coast Path",
			"name"		: "Wales Coast",
			"attr"		: "ers",
			"dist_route"	: 865,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.442618,
			"longitude"	: -3.477173,
			"zoom"		: 8,
			"custom"	: ""
		},
		"wantsum.walk" : {
			"fullname"	: "Wantsum Walk",
			"name"		: "Wantsum Walk",
			"attr"		: "ers",
			"dist_route"	: 19,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.356346,
			"longitude"	: 1.214676,
			"zoom"		: 12,
			"custom"	: ""
		},
		"welsh.3000s" : {
			"fullname"	: "Welsh 3000s",
			"name"		: "Welsh 3000s",
			"attr"		: "ersx",
			"dist_route"	: 24,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.133178,
			"longitude"	: -4.017906,
			"zoom"		: 12,
			"custom"	: "peaks"
		},
		"west.highland.way" : {
			"fullname"	: "West Highland Way &mdash; National Trail",
			"name"		: "West Highland Way",
			"attr"		: "ers",
			"dist_route"	: 94,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.328721,
			"longitude"	: -4.743347,
			"zoom"		: 9,
			"custom"	: ""
		},
		"west.somerset.coast" : {
			"fullname"	: "West Somerset Coast Path",
			"name"		: "West Somerset Coast",
			"attr"		: "cehrs",
			"dist_route"	: 25,
			"date_start"	: "2013-04-29",
			"date_end"	: "2013-04-30",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 27,
			"complete"	: 100,
			"latitude"	: 51.172886,
			"longitude"	: -3.258820,
			"zoom"		: 11,
			"custom"	: ""
		},
		"west.sussex.literary" : {
			"fullname"	: "West Sussex Literary Trail",
			"name"		: "West Sussex Literary",
			"attr"		: "ers",
			"dist_route"	: 49,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.953669,
			"longitude"	: -0.526657,
			"zoom"		: 11,
			"custom"	: ""
		},
		"wey.navigations" : {
			"fullname"	: "Wey Navigations",
			"name"		: "Wey Navigations",
			"attr"		: "ehrstv",
			"dist_route"	: 19,
			"date_start"	: "2013-02-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 17,
			"complete"	: 89,
			"latitude"	: 51.282535,
			"longitude"	: -0.534897,
			"zoom"		: 11,
			"custom"	: ""
		},
		"white.cliffs" : {
			"fullname"	: "White Cliffs Country Trails",
			"name"		: "White Cliffs",
			"attr"		: "ehrs",
			"dist_route"	: 9,
			"date_start"	: "2013-01-14",
			"date_end"	: "2013-01-14",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 10,
			"complete"	: 100,
			"latitude"	: 51.174823,
			"longitude"	: 1.358528,
			"zoom"		: 12,
			"custom"	: ""
		},
		"wirral.circular" : {
			"fullname"	: "Wirral Circular Trail",
			"name"		: "Wirral Circular",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.358338,
			"longitude"	: -3.059692,
			"zoom"		: 11,
			"custom"	: ""
		},
		"wysis.way" : {
			"fullname"	: "Wysis Way",
			"name"		: "Wysis Way",
			"attr"		: "ehrst",
			"dist_route"	: 52,
			"date_start"	: "2013-02-28",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 13,
			"latitude"	: 51.778887,
			"longitude"	: -2.395020,
			"zoom"		: 10,
			"custom"	: ""
		},
		"yorkshire.three.peaks" : {
			"fullname"	: "Yorkshire Three Peaks",
			"name"		: "Yorkshire Three Peaks",
			"attr"		: "ehrsx",
			"dist_route"	: 24,
			"date_start"	: "2011-08-03",
			"date_end"	: "2011-08-03",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 24,
			"complete"	: 100,
			"latitude"	: 54.188959,
			"longitude"	: -2.333221,
			"zoom"		: 12,
			"custom"	: "peaks"
		},
		"yorkshire.wolds" : {
			"fullname"	: "Yorkshire Wolds Way &mdash; National Trail",
			"name"		: "Yorkshire Wolds Way",
			"attr"		: "ers",
			"dist_route"	: 79,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.963357,
			"longitude"	: -0.440826,
			"zoom"		: 10,
			"custom"	: ""
		},
	};

	return route_list;
}

