function init_routes()
{
	var route_list = {
		"1066.country.walk" : {
			"fullname"	: "1066 Country Walk",
			"name"		: "1066 Country Walk",
			"attr"		: "cehrst",
			"dist_route"	: 32,
			"date_start"	: "2013-01-09",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 30,
			"complete"	: 93,
			"latitude"	: 50.884800,
			"longitude"	: 0.521851,
			"zoom"		: 11,
			"custom"	: ""
		},
		"coast.to.coast.alternative" : {
			"fullname"	: "Alternative Coast to Coast",
			"name"		: "Alternative Coast to Coast",
			"attr"		: "ers",
			"dist_route"	: 200,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.829200,
			"longitude"	: -2.433470,
			"zoom"		: 8,
			"custom"	: ""
		},
		"annandale.way" : {
			"fullname"	: "Annandale Way",
			"name"		: "Annandale Way",
			"attr"		: "ers",
			"dist_route"	: 53,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.160900,
			"longitude"	: -3.305510,
			"zoom"		: 10,
			"custom"	: ""
		},
		"arden.way" : {
			"fullname"	: "Arden Way",
			"name"		: "Arden Way",
			"attr"		: "cehrst",
			"dist_route"	: 27,
			"date_start"	: "2012-12-18",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 8,
			"complete"	: 28,
			"latitude"	: 52.264400,
			"longitude"	: -1.849140,
			"zoom"		: 12,
			"custom"	: ""
		},
		"join.2" : {
			"fullname"	: "Aust to Chepstow",
			"name"		: "Aust to Chepstow",
			"attr"		: "ehs",
			"dist_route"	: 5,
			"date_start"	: "2013-05-07",
			"date_end"	: "2013-05-07",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 5,
			"complete"	: 100,
			"latitude"	: 51.621700,
			"longitude"	: -2.654060,
			"zoom"		: 13,
			"custom"	: ""
		},
		"ayrshire.coast" : {
			"fullname"	: "Ayrshire Coastal Path",
			"name"		: "Ayrshire Coast",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.463300,
			"longitude"	: -4.812010,
			"zoom"		: 8,
			"custom"	: ""
		},
		"berwick.boundary" : {
			"fullname"	: "Berwick Borough Boundary Walk",
			"name"		: "Berwick Boundary",
			"attr"		: "ers",
			"dist_route"	: 109,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.583000,
			"longitude"	: -2.024230,
			"zoom"		: 10,
			"custom"	: ""
		},
		"berwick.coast" : {
			"fullname"	: "Berwickshire Coastal Path",
			"name"		: "Berwick Coast",
			"attr"		: "ers",
			"dist_route"	: 29,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.866700,
			"longitude"	: -2.166670,
			"zoom"		: 11,
			"custom"	: ""
		},
		"join.1" : {
			"fullname"	: "Bridgwater to Avonmouth",
			"name"		: "Bridgwater to Avonmouth",
			"attr"		: "cehs",
			"dist_route"	: 62,
			"date_start"	: "2013-05-01",
			"date_end"	: "2013-05-04",
			"days_walked"	: 4,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 62,
			"complete"	: 100,
			"latitude"	: 51.346100,
			"longitude"	: -2.923740,
			"zoom"		: 10,
			"custom"	: ""
		},
		"calderdale.way" : {
			"fullname"	: "Calderdale Way",
			"name"		: "Calderdale Way",
			"attr"		: "ers",
			"dist_route"	: 50,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.723900,
			"longitude"	: -1.925350,
			"zoom"		: 11,
			"custom"	: ""
		},
		"central.scottish.way" : {
			"fullname"	: "Central Scottish Way",
			"name"		: "Central Scottish Way",
			"attr"		: "ers",
			"dist_route"	: 147,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.856800,
			"longitude"	: -3.142090,
			"zoom"		: 8,
			"custom"	: ""
		},
		"cleveland.way" : {
			"fullname"	: "Cleveland Way - National Trail",
			"name"		: "Cleveland Way",
			"attr"		: "cehrst",
			"dist_route"	: 107,
			"date_start"	: "2012-10-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 13,
			"complete"	: 12,
			"latitude"	: 54.404500,
			"longitude"	: -0.802002,
			"zoom"		: 10,
			"custom"	: ""
		},
		"coast.to.coast.scotland" : {
			"fullname"	: "Coast to Coast Scotland",
			"name"		: "Coast to Coast Scotland",
			"attr"		: "ers",
			"dist_route"	: 134,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.398700,
			"longitude"	: -4.213260,
			"zoom"		: 8,
			"custom"	: ""
		},
		"coast.to.coast" : {
			"fullname"	: "Coast to Coast",
			"name"		: "Coast to Coast",
			"attr"		: "cehrs",
			"dist_route"	: 188,
			"date_start"	: "2012-09-28",
			"date_end"	: "2012-10-10",
			"days_walked"	: 13,
			"days_camped"	: 10,
			"days_other"	: 3,
			"dist_walked"	: 188,
			"complete"	: 100,
			"latitude"	: 54.425300,
			"longitude"	: -2.032470,
			"zoom"		: 8,
			"custom"	: ""
		},
		"cotswold.canals" : {
			"fullname"	: "Cotswold Canals Walk",
			"name"		: "Cotswold Canals",
			"attr"		: "cehrst",
			"dist_route"	: 43,
			"date_start"	: "2013-02-28",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 24,
			"complete"	: 55,
			"latitude"	: 51.723600,
			"longitude"	: -2.028350,
			"zoom"		: 10,
			"custom"	: ""
		},
		"cotswold.way" : {
			"fullname"	: "Cotswold Way - National Trail",
			"name"		: "Cotswold Way",
			"attr"		: "ers",
			"dist_route"	: 101,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.795000,
			"longitude"	: -2.153320,
			"zoom"		: 9,
			"custom"	: ""
		},
		"coventry.way" : {
			"fullname"	: "Coventry Way",
			"name"		: "Coventry Way",
			"attr"		: "ehrst",
			"dist_route"	: 41,
			"date_start"	: "2012-12-18",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 4,
			"complete"	: 9,
			"latitude"	: 52.410000,
			"longitude"	: -1.492080,
			"zoom"		: 11,
			"custom"	: ""
		},
		"cross.cotswold" : {
			"fullname"	: "Cross Cotswold Pathway",
			"name"		: "Cross Cotswold",
			"attr"		: "ers",
			"dist_route"	: 90,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.801800,
			"longitude"	: -1.881410,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbria.coast" : {
			"fullname"	: "Cumbria Coastal Way",
			"name"		: "Cumbria Coast",
			"attr"		: "ers",
			"dist_route"	: 192,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.535400,
			"longitude"	: -3.098150,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbria.way" : {
			"fullname"	: "Cumbria Way",
			"name"		: "Cumbria Way",
			"attr"		: "ers",
			"dist_route"	: 74,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.557700,
			"longitude"	: -3.081670,
			"zoom"		: 9,
			"custom"	: ""
		},
		"cumbrian.trident" : {
			"fullname"	: "Cumbrian Classic Trident Walk",
			"name"		: "Cumbrian Trident",
			"attr"		: "ers",
			"dist_route"	: 97,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.509100,
			"longitude"	: -3.081670,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.walk" : {
			"fullname"	: "Dales Walk",
			"name"		: "Dales Walk",
			"attr"		: "cehrst",
			"dist_route"	: 73,
			"date_start"	: "2012-10-04",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 1,
			"dist_walked"	: 13,
			"complete"	: 18,
			"latitude"	: 54.372600,
			"longitude"	: -2.050320,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.way" : {
			"fullname"	: "Dales Way",
			"name"		: "Dales Way",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.191400,
			"longitude"	: -2.296140,
			"zoom"		: 9,
			"custom"	: ""
		},
		"dane.valley" : {
			"fullname"	: "Dane Valley Way",
			"name"		: "Dane Valley",
			"attr"		: "ers",
			"dist_route"	: 41,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.206000,
			"longitude"	: -2.142330,
			"zoom"		: 10,
			"custom"	: ""
		},
		"cotswold.diamond" : {
			"fullname"	: "Diamond Way North Cotswold",
			"name"		: "Cotswold Diamond",
			"attr"		: "ers",
			"dist_route"	: 65,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.940900,
			"longitude"	: -1.754380,
			"zoom"		: 11,
			"custom"	: ""
		},
		"e2" : {
			"fullname"	: "E2 Dover to Stranraer",
			"name"		: "E2",
			"attr"		: "cehrstv",
			"dist_route"	: 890,
			"date_start"	: "2010-09-22",
			"date_end"	: "",
			"days_walked"	: 40,
			"days_camped"	: 34,
			"days_other"	: 4,
			"dist_walked"	: 700,
			"complete"	: 79,
			"latitude"	: 54.699200,
			"longitude"	: -4.943850,
			"zoom"		: 6,
			"custom"	: ""
		},
		"e8" : {
			"fullname"	: "E8 Hull to Liverpool",
			"name"		: "E8",
			"attr"		: "ers",
			"dist_route"	: 179,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.497800,
			"longitude"	: -1.642460,
			"zoom"		: 8,
			"custom"	: ""
		},
		"e9" : {
			"fullname"	: "E9 Dover to Plymouth",
			"name"		: "E9",
			"attr"		: "cefhrsvx",
			"dist_route"	: 448,
			"date_start"	: "2012-06-13",
			"date_end"	: "2013-01-12",
			"days_walked"	: 24,
			"days_camped"	: 18,
			"days_other"	: 4,
			"dist_walked"	: 448,
			"complete"	: 100,
			"latitude"	: 50.590200,
			"longitude"	: -1.450190,
			"zoom"		: 7,
			"custom"	: "ferry_icon"
		},
		"elham.valley" : {
			"fullname"	: "Elham Valley Way",
			"name"		: "Elham Valley",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.184900,
			"longitude"	: 1.119230,
			"zoom"		: 11,
			"custom"	: ""
		},
		"esk.valley" : {
			"fullname"	: "Esk Valley Walk",
			"name"		: "Esk Valley",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.428500,
			"longitude"	: -0.790329,
			"zoom"		: 11,
			"custom"	: ""
		},
		"eskdale.way" : {
			"fullname"	: "Eskdale Way",
			"name"		: "Eskdale Way",
			"attr"		: "ers",
			"dist_route"	: 88,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.434900,
			"longitude"	: -0.843201,
			"zoom"		: 11,
			"custom"	: ""
		},
		"etherow.goyt.valley" : {
			"fullname"	: "Etherow - Goyt Valley Way",
			"name"		: "Etherow - Goyt Valley",
			"attr"		: "ers",
			"dist_route"	: 14,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.428600,
			"longitude"	: -2.040370,
			"zoom"		: 12,
			"custom"	: ""
		},
		"fife.coast" : {
			"fullname"	: "Fife Coastal Path",
			"name"		: "Fife Coast",
			"attr"		: "ers",
			"dist_route"	: 115,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.238000,
			"longitude"	: -3.228610,
			"zoom"		: 10,
			"custom"	: ""
		},
		"five.degrees.west" : {
			"fullname"	: "Five Degrees West Challenge",
			"name"		: "Five Degrees West",
			"attr"		: "cehrstx",
			"dist_route"	: 289,
			"date_start"	: "2013-06-10",
			"date_end"	: "",
			"days_walked"	: 8,
			"days_camped"	: 7,
			"days_other"	: 1,
			"dist_walked"	: 113,
			"complete"	: 39,
			"latitude"	: 57.106400,
			"longitude"	: -4.943850,
			"zoom"		: 7,
			"custom"	: "line,crossovers"
		},
		"gloucestershire.way" : {
			"fullname"	: "Gloucestershire Way",
			"name"		: "Gloucestershire Way",
			"attr"		: "cehrs",
			"dist_route"	: 98,
			"date_start"	: "2013-08-18",
			"date_end"	: "2013-08-23",
			"days_walked"	: 6,
			"days_camped"	: 5,
			"days_other"	: 0,
			"dist_walked"	: 98,
			"complete"	: 100,
			"latitude"	: 51.808600,
			"longitude"	: -2.230230,
			"zoom"		: 10,
			"custom"	: ""
		},
		"glyndwrs.way" : {
			"fullname"	: "Glyndwr's Way - National Trail",
			"name"		: "Glyndwr's Way",
			"attr"		: "ers",
			"dist_route"	: 137,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.538800,
			"longitude"	: -3.361820,
			"zoom"		: 10,
			"custom"	: ""
		},
		"join.3" : {
			"fullname"	: "Gourock to Toward Point",
			"name"		: "Gourock to Toward Point",
			"attr"		: "efhsx",
			"dist_route"	: 7,
			"date_start"	: "2013-06-10",
			"date_end"	: "2013-06-10",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 100,
			"latitude"	: 55.899200,
			"longitude"	: -4.889600,
			"zoom"		: 11,
			"custom"	: "ferry_icon"
		},
		"goyt.way" : {
			"fullname"	: "Goyt Way",
			"name"		: "Goyt Way",
			"attr"		: "ers",
			"dist_route"	: 10,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.371700,
			"longitude"	: -2.028350,
			"zoom"		: 12,
			"custom"	: ""
		},
		"great.english.walk" : {
			"fullname"	: "Great English Walk",
			"name"		: "Great English Walk",
			"attr"		: "ers",
			"dist_route"	: 586,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.638100,
			"longitude"	: -2.065430,
			"zoom"		: 7,
			"custom"	: ""
		},
		"great.glen.way" : {
			"fullname"	: "Great Glen Way - National Trail",
			"name"		: "Great Glen Way",
			"attr"		: "ers",
			"dist_route"	: 73,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.166000,
			"longitude"	: -4.600520,
			"zoom"		: 9,
			"custom"	: ""
		},
		"gritstone.trail" : {
			"fullname"	: "Gritstone Trail",
			"name"		: "Gritstone Trail",
			"attr"		: "cehrst",
			"dist_route"	: 35,
			"date_start"	: "2012-12-12",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 21,
			"complete"	: 59,
			"latitude"	: 53.217500,
			"longitude"	: -2.140960,
			"zoom"		: 10,
			"custom"	: ""
		},
		"hadrians.coast" : {
			"fullname"	: "Hadrian's Coastal Route",
			"name"		: "Hadrian's Coast",
			"attr"		: "ers",
			"dist_route"	: 78,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.678600,
			"longitude"	: -3.370060,
			"zoom"		: 9,
			"custom"	: ""
		},
		"hadrians.wall" : {
			"fullname"	: "Hadrian's Wall Path - National Trail",
			"name"		: "Hadrian's Wall",
			"attr"		: "ehrst",
			"dist_route"	: 87,
			"date_start"	: "2012-10-14",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 9,
			"complete"	: 11,
			"latitude"	: 54.963400,
			"longitude"	: -2.364810,
			"zoom"		: 9,
			"custom"	: ""
		},
		"hangers.way" : {
			"fullname"	: "Hanger's Way",
			"name"		: "Hanger's Way",
			"attr"		: "ers",
			"dist_route"	: 21,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.062100,
			"longitude"	: -0.925598,
			"zoom"		: 10,
			"custom"	: ""
		},
		"heart.of.england" : {
			"fullname"	: "Heart of England Way",
			"name"		: "Heart of England",
			"attr"		: "cehrst",
			"dist_route"	: 104,
			"date_start"	: "2012-12-16",
			"date_end"	: "",
			"days_walked"	: 6,
			"days_camped"	: 5,
			"days_other"	: 0,
			"dist_walked"	: 100,
			"complete"	: 96,
			"latitude"	: 52.357200,
			"longitude"	: -1.845700,
			"zoom"		: 9,
			"custom"	: ""
		},
		"heart.of.snowdonia" : {
			"fullname"	: "Heart of Snowdonia",
			"name"		: "Heart of Snowdonia",
			"attr"		: "ers",
			"dist_route"	: 49,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.081200,
			"longitude"	: -4.011380,
			"zoom"		: 11,
			"custom"	: ""
		},
		"hobblers.way" : {
			"fullname"	: "Hobblers Way",
			"name"		: "Hobblers Way",
			"attr"		: "ers",
			"dist_route"	: 192,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.221100,
			"longitude"	: -1.071170,
			"zoom"		: 8,
			"custom"	: ""
		},
		"isaacs.tea.trail" : {
			"fullname"	: "Isaac's Tea Trail",
			"name"		: "Isaac's Tea Trail",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.849900,
			"longitude"	: -2.347640,
			"zoom"		: 12,
			"custom"	: ""
		},
		"isle.of.wight.coast" : {
			"fullname"	: "Isle of Wight Coastal Path",
			"name"		: "Isle of Wight Coast",
			"attr"		: "cefhrsx",
			"dist_route"	: 68,
			"date_start"	: "2012-12-30",
			"date_end"	: "2013-01-02",
			"days_walked"	: 4,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 68,
			"complete"	: 100,
			"latitude"	: 50.670800,
			"longitude"	: -1.321790,
			"zoom"		: 11,
			"custom"	: "ferry_icon"
		},
		"itchen.way" : {
			"fullname"	: "Itchen Way",
			"name"		: "Itchen Way",
			"attr"		: "ers",
			"dist_route"	: 30,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.984400,
			"longitude"	: -1.290210,
			"zoom"		: 11,
			"custom"	: ""
		},
		"kent.coast" : {
			"fullname"	: "Kent Coast Path",
			"name"		: "Kent Coast",
			"attr"		: "cehrsv",
			"dist_route"	: 205,
			"date_start"	: "2013-01-11",
			"date_end"	: "2013-01-21",
			"days_walked"	: 10,
			"days_camped"	: 8,
			"days_other"	: 2,
			"dist_walked"	: 205,
			"complete"	: 100,
			"latitude"	: 51.198300,
			"longitude"	: 0.832214,
			"zoom"		: 9,
			"custom"	: ""
		},
		"lancashire.coast" : {
			"fullname"	: "Lancashire Coastal Way",
			"name"		: "Lancashire Coast",
			"attr"		: "ers",
			"dist_route"	: 68,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.956100,
			"longitude"	: -2.860560,
			"zoom"		: 10,
			"custom"	: ""
		},
		"lyke.wake.walk" : {
			"fullname"	: "Lyke Wake Walk",
			"name"		: "Lyke Wake Walk",
			"attr"		: "cehrst",
			"dist_route"	: 39,
			"date_start"	: "2012-10-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 22,
			"complete"	: 56,
			"latitude"	: 54.398100,
			"longitude"	: -0.892639,
			"zoom"		: 10,
			"custom"	: ""
		},
		"macmillan.abbotsbury.langport" : {
			"fullname"	: "Macmillan Abbotsbury Langport Link",
			"name"		: "Macmillan Abbotsbury Langport",
			"attr"		: "ers",
			"dist_route"	: 40,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.875300,
			"longitude"	: -2.712250,
			"zoom"		: 10,
			"custom"	: ""
		},
		"macmillan.way.west" : {
			"fullname"	: "Macmillan Way West",
			"name"		: "Macmillan Way West",
			"attr"		: "ers",
			"dist_route"	: 102,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.110400,
			"longitude"	: -3.342590,
			"zoom"		: 9,
			"custom"	: ""
		},
		"macmillan.way" : {
			"fullname"	: "Macmillan Way",
			"name"		: "Macmillan Way",
			"attr"		: "ers",
			"dist_route"	: 287,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.099800,
			"longitude"	: -1.065670,
			"zoom"		: 7,
			"custom"	: ""
		},
		"midshires.way" : {
			"fullname"	: "Midshires Way",
			"name"		: "Midshires Way",
			"attr"		: "ers",
			"dist_route"	: 224,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.636400,
			"longitude"	: -1.334840,
			"zoom"		: 8,
			"custom"	: ""
		},
		"monarchs.way" : {
			"fullname"	: "Monarch's Way",
			"name"		: "Monarch's Way",
			"attr"		: "ers",
			"dist_route"	: 565,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.655500,
			"longitude"	: -2.147830,
			"zoom"		: 8,
			"custom"	: ""
		},
		"mull.of.galloway.trail" : {
			"fullname"	: "Mull of Galloway Trail",
			"name"		: "Mull of Galloway Trail",
			"attr"		: "ers",
			"dist_route"	: 36,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.846600,
			"longitude"	: -4.980930,
			"zoom"		: 10,
			"custom"	: ""
		},
		"munros" : {
			"fullname"	: "Munros - Scotland",
			"name"		: "Munros",
			"attr"		: "ap",
			"dist_route"	: 0,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.670600,
			"longitude"	: -4.224240,
			"zoom"		: 7,
			"custom"	: ""
		},
		"nelson.way" : {
			"fullname"	: "Nelson Way",
			"name"		: "Nelson Way",
			"attr"		: "ers",
			"dist_route"	: 406,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.730400,
			"longitude"	: 0.318604,
			"zoom"		: 8,
			"custom"	: ""
		},
		"north.downs" : {
			"fullname"	: "North Downs Way - National Trail",
			"name"		: "North Downs",
			"attr"		: "cehrsv",
			"dist_route"	: 128,
			"date_start"	: "2013-01-12",
			"date_end"	: "2013-02-08",
			"days_walked"	: 7,
			"days_camped"	: 5,
			"days_other"	: 1,
			"dist_walked"	: 128,
			"complete"	: 100,
			"latitude"	: 51.063800,
			"longitude"	: 0.285645,
			"zoom"		: 9,
			"custom"	: ""
		},
		"north.to.the.cape" : {
			"fullname"	: "North to the Cape",
			"name"		: "North to the Cape",
			"attr"		: "ers",
			"dist_route"	: 218,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.671800,
			"longitude"	: -5.026250,
			"zoom"		: 8,
			"custom"	: ""
		},
		"northumberland.coast" : {
			"fullname"	: "Northumberland Coast Path",
			"name"		: "Northumberland Coast",
			"attr"		: "ers",
			"dist_route"	: 64,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.522400,
			"longitude"	: -1.782530,
			"zoom"		: 9,
			"custom"	: ""
		},
		"offas.dyke" : {
			"fullname"	: "Offa's Dyke Path - National Trail",
			"name"		: "Offa's Dyke",
			"attr"		: "cehrs",
			"dist_route"	: 179,
			"date_start"	: "2013-05-08",
			"date_end"	: "2013-05-16",
			"days_walked"	: 9,
			"days_camped"	: 9,
			"days_other"	: 1,
			"dist_walked"	: 179,
			"complete"	: 100,
			"latitude"	: 52.479400,
			"longitude"	: -3.246460,
			"zoom"		: 8,
			"custom"	: ""
		},
		"oldham.way" : {
			"fullname"	: "Oldham Way",
			"name"		: "Oldham Way",
			"attr"		: "cehrst",
			"dist_route"	: 39,
			"date_start"	: "2010-09-22",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 12,
			"complete"	: 30,
			"latitude"	: 53.544200,
			"longitude"	: -2.065090,
			"zoom"		: 12,
			"custom"	: ""
		},
		"oxford.canal" : {
			"fullname"	: "Oxford Canal Walk",
			"name"		: "Oxford Canal",
			"attr"		: "cehrst",
			"dist_route"	: 84,
			"date_start"	: "2013-02-23",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 11,
			"complete"	: 13,
			"latitude"	: 52.104800,
			"longitude"	: -0.997009,
			"zoom"		: 9,
			"custom"	: ""
		},
		"oxford.green.belt" : {
			"fullname"	: "Oxford Green Belt Way",
			"name"		: "Oxford Green Belt",
			"attr"		: "cehrs",
			"dist_route"	: 55,
			"date_start"	: "2013-02-24",
			"date_end"	: "2013-03-07",
			"days_walked"	: 4,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 55,
			"complete"	: 100,
			"latitude"	: 51.743600,
			"longitude"	: -1.208500,
			"zoom"		: 11,
			"custom"	: ""
		},
		"oxfordshire.way" : {
			"fullname"	: "Oxfordshire Way",
			"name"		: "Oxfordshire Way",
			"attr"		: "cehrst",
			"dist_route"	: 70,
			"date_start"	: "2012-12-21",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 29,
			"complete"	: 41,
			"latitude"	: 51.720200,
			"longitude"	: -1.332090,
			"zoom"		: 10,
			"custom"	: ""
		},
		"peddars.way.and.norfolk.coast" : {
			"fullname"	: "Peddars Way and Norfolk Coast Path - National Trail",
			"name"		: "Peddars Way and Norfolk Coast",
			"attr"		: "ers",
			"dist_route"	: 97,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.757900,
			"longitude"	: 0.892639,
			"zoom"		: 9,
			"custom"	: ""
		},
		"pembrokeshire.coast" : {
			"fullname"	: "Pembrokeshire Coast Path - National Trail",
			"name"		: "Pembrokeshire Coast",
			"attr"		: "cefhrsx",
			"dist_route"	: 177,
			"date_start"	: "2013-07-30",
			"date_end"	: "2013-08-08",
			"days_walked"	: 10,
			"days_camped"	: 9,
			"days_other"	: 0,
			"dist_walked"	: 177,
			"complete"	: 100,
			"latitude"	: 51.849400,
			"longitude"	: -4.879300,
			"zoom"		: 10,
			"custom"	: "ferry_icon"
		},
		"pennine.bridleway" : {
			"fullname"	: "Pennine Bridleway - National Trail",
			"name"		: "Pennine Bridleway",
			"attr"		: "ers",
			"dist_route"	: 163,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.690200,
			"longitude"	: -2.164310,
			"zoom"		: 8,
			"custom"	: ""
		},
		"pennine.way" : {
			"fullname"	: "Pennine Way - National Trail",
			"name"		: "Pennine Way",
			"attr"		: "cehrs",
			"dist_route"	: 261,
			"date_start"	: "2010-09-20",
			"date_end"	: "2012-10-18",
			"days_walked"	: 16,
			"days_camped"	: 15,
			"days_other"	: 3,
			"dist_walked"	: 261,
			"complete"	: 100,
			"latitude"	: 53.994900,
			"longitude"	: -0.769043,
			"zoom"		: 7,
			"custom"	: ""
		},
		"pilgrims.way" : {
			"fullname"	: "Pilgrim's Way",
			"name"		: "Pilgrim's Way",
			"attr"		: "cehrst",
			"dist_route"	: 150,
			"date_start"	: "2013-02-04",
			"date_end"	: "",
			"days_walked"	: 5,
			"days_camped"	: 4,
			"days_other"	: 0,
			"dist_walked"	: 103,
			"complete"	: 69,
			"latitude"	: 51.025800,
			"longitude"	: -0.131836,
			"zoom"		: 9,
			"custom"	: ""
		},
		"ribble.way" : {
			"fullname"	: "Ribble Way",
			"name"		: "Ribble Way",
			"attr"		: "ers",
			"dist_route"	: 69,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.964200,
			"longitude"	: -2.419740,
			"zoom"		: 9,
			"custom"	: ""
		},
		"ridgeway" : {
			"fullname"	: "Ridgeway - National Trail",
			"name"		: "Ridgeway",
			"attr"		: "ers",
			"dist_route"	: 86,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.614600,
			"longitude"	: -1.186520,
			"zoom"		: 10,
			"custom"	: ""
		},
		"river.parrett" : {
			"fullname"	: "River Parrett Trail",
			"name"		: "River Parrett",
			"attr"		: "cehrst",
			"dist_route"	: 46,
			"date_start"	: "2013-04-30",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 12,
			"complete"	: 26,
			"latitude"	: 51.024100,
			"longitude"	: -2.855070,
			"zoom"		: 10,
			"custom"	: ""
		},
		"rob.roy.way" : {
			"fullname"	: "Rob Roy Way",
			"name"		: "Rob Roy Way",
			"attr"		: "ers",
			"dist_route"	: 79,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.409300,
			"longitude"	: -4.095150,
			"zoom"		: 9,
			"custom"	: ""
		},
		"rochdale.way" : {
			"fullname"	: "Rochdale Way",
			"name"		: "Rochdale Way",
			"attr"		: "ers",
			"dist_route"	: 48,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.613100,
			"longitude"	: -2.146450,
			"zoom"		: 12,
			"custom"	: ""
		},
		"saxon.shore" : {
			"fullname"	: "Saxon Shore Way",
			"name"		: "Saxon Shore",
			"attr"		: "cehrst",
			"dist_route"	: 163,
			"date_start"	: "2013-01-12",
			"date_end"	: "",
			"days_walked"	: 9,
			"days_camped"	: 5,
			"days_other"	: 2,
			"dist_walked"	: 100,
			"complete"	: 62,
			"latitude"	: 51.169000,
			"longitude"	: 0.818481,
			"zoom"		: 9,
			"custom"	: ""
		},
		"sefton.coast" : {
			"fullname"	: "Sefton Coastal Path",
			"name"		: "Sefton Coast",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.581500,
			"longitude"	: -3.019870,
			"zoom"		: 11,
			"custom"	: ""
		},
		"severn.way" : {
			"fullname"	: "Severn Way",
			"name"		: "Severn Way",
			"attr"		: "cehrst",
			"dist_route"	: 271,
			"date_start"	: "2013-05-04",
			"date_end"	: "",
			"days_walked"	: 7,
			"days_camped"	: 5,
			"days_other"	: 0,
			"dist_walked"	: 88,
			"complete"	: 32,
			"latitude"	: 52.147000,
			"longitude"	: -2.982790,
			"zoom"		: 8,
			"custom"	: ""
		},
		"shakespeares.way" : {
			"fullname"	: "Shakespeare's Way",
			"name"		: "Shakespeare's Way",
			"attr"		: "ers",
			"dist_route"	: 129,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.779700,
			"longitude"	: -1.197510,
			"zoom"		: 9,
			"custom"	: ""
		},
		"snowdon.horseshoe" : {
			"fullname"	: "Snowdon Horseshoe",
			"name"		: "Snowdon Horseshoe",
			"attr"		: "ehrs",
			"dist_route"	: 8,
			"date_start"	: "2005-08-20",
			"date_end"	: "2005-08-20",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 8,
			"complete"	: 100,
			"latitude"	: 53.069200,
			"longitude"	: -4.050010,
			"zoom"		: 14,
			"custom"	: ""
		},
		"snowdonia.to.the.gower" : {
			"fullname"	: "Snowdonia to the Gower",
			"name"		: "Snowdonia to the Gower",
			"attr"		: "ers",
			"dist_route"	: 209,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.425900,
			"longitude"	: -3.850710,
			"zoom"		: 8,
			"custom"	: ""
		},
		"solent.way" : {
			"fullname"	: "Solent Way",
			"name"		: "Solent Way",
			"attr"		: "cefhrstx",
			"dist_route"	: 61,
			"date_start"	: "2012-12-30",
			"date_end"	: "",
			"days_walked"	: 5,
			"days_camped"	: 2,
			"days_other"	: 1,
			"dist_walked"	: 57,
			"complete"	: 93,
			"latitude"	: 50.739900,
			"longitude"	: -1.196140,
			"zoom"		: 10,
			"custom"	: "ferry_icon"
		},
		"south.downs" : {
			"fullname"	: "South Downs Way - National Trail",
			"name"		: "South Downs",
			"attr"		: "cehrst",
			"dist_route"	: 98,
			"date_start"	: "2013-01-06",
			"date_end"	: "",
			"days_walked"	: 4,
			"days_camped"	: 3,
			"days_other"	: 0,
			"dist_walked"	: 72,
			"complete"	: 74,
			"latitude"	: 50.786800,
			"longitude"	: -0.359802,
			"zoom"		: 9,
			"custom"	: ""
		},
		"south.tyne.trail" : {
			"fullname"	: "South Tyne Trail",
			"name"		: "South Tyne Trail",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.844200,
			"longitude"	: -2.462310,
			"zoom"		: 11,
			"custom"	: ""
		},
		"south.west.coast" : {
			"fullname"	: "South West Coast Path - National Trail",
			"name"		: "South West Coast",
			"attr"		: "cefhrsx",
			"dist_route"	: 622,
			"date_start"	: "2012-04-30",
			"date_end"	: "2012-06-23",
			"days_walked"	: 36,
			"days_camped"	: 32,
			"days_other"	: 4,
			"dist_walked"	: 622,
			"complete"	: 100,
			"latitude"	: 50.457500,
			"longitude"	: -4.037480,
			"zoom"		: 8,
			"custom"	: "ferry_icon"
		},
		"coast.to.coast.south" : {
			"fullname"	: "Southern Coast to Coast",
			"name"		: "Southern Coast to Coast",
			"attr"		: "ers",
			"dist_route"	: 278,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.141400,
			"longitude"	: -1.142580,
			"zoom"		: 8,
			"custom"	: ""
		},
		"southern.upland.way" : {
			"fullname"	: "Southern Upland Way - National Trail",
			"name"		: "Southern Upland Way",
			"attr"		: "ers",
			"dist_route"	: 211,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.394700,
			"longitude"	: -3.543090,
			"zoom"		: 8,
			"custom"	: ""
		},
		"speyside.way" : {
			"fullname"	: "Speyside Way - National Trail",
			"name"		: "Speyside Way",
			"attr"		: "ers",
			"dist_route"	: 66,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 57.405000,
			"longitude"	: -3.337100,
			"zoom"		: 10,
			"custom"	: ""
		},
		"st.cuthberts" : {
			"fullname"	: "St Cuthbert's Way",
			"name"		: "St Cuthbert's Way",
			"attr"		: "ers",
			"dist_route"	: 64,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 55.550400,
			"longitude"	: -2.254940,
			"zoom"		: 10,
			"custom"	: ""
		},
		"staffordshire.gritstone" : {
			"fullname"	: "Staffordshire Gritstone Walk",
			"name"		: "Staffordshire Gritstone",
			"attr"		: "ers",
			"dist_route"	: 35,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.158300,
			"longitude"	: -1.947670,
			"zoom"		: 12,
			"custom"	: ""
		},
		"staffordshire.moorlands" : {
			"fullname"	: "Staffordshire Moorlands Challenge Walk",
			"name"		: "Staffordshire Moorlands",
			"attr"		: "ehrst",
			"dist_route"	: 23,
			"date_start"	: "2012-12-14",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 29,
			"latitude"	: 53.000700,
			"longitude"	: -1.883120,
			"zoom"		: 12,
			"custom"	: ""
		},
		"staffordshire.way" : {
			"fullname"	: "Staffordshire Way",
			"name"		: "Staffordshire Way",
			"attr"		: "cehrst",
			"dist_route"	: 97,
			"date_start"	: "2012-12-13",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 2,
			"days_other"	: 0,
			"dist_walked"	: 45,
			"complete"	: 47,
			"latitude"	: 52.792800,
			"longitude"	: -2.046200,
			"zoom"		: 9,
			"custom"	: ""
		},
		"standedge.trail" : {
			"fullname"	: "Standedge Trail",
			"name"		: "Standedge Trail",
			"attr"		: "ers",
			"dist_route"	: 11,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.585900,
			"longitude"	: -1.959690,
			"zoom"		: 13,
			"custom"	: ""
		},
		"staunton.way" : {
			"fullname"	: "Staunton Way",
			"name"		: "Staunton Way",
			"attr"		: "ers",
			"dist_route"	: 21,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.927900,
			"longitude"	: -0.952377,
			"zoom"		: 12,
			"custom"	: ""
		},
		"suffolk.coast.and.heath" : {
			"fullname"	: "Suffolk Coast and Heath Path",
			"name"		: "Suffolk Coast and Heath",
			"attr"		: "ers",
			"dist_route"	: 58,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.209300,
			"longitude"	: 1.610870,
			"zoom"		: 10,
			"custom"	: ""
		},
		"tameside.trail" : {
			"fullname"	: "Tameside Trail",
			"name"		: "Tameside Trail",
			"attr"		: "ehrst",
			"dist_route"	: 35,
			"date_start"	: "2012-12-11",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 10,
			"complete"	: 28,
			"latitude"	: 53.478900,
			"longitude"	: -2.075390,
			"zoom"		: 12,
			"custom"	: ""
		},
		"tandridge.border" : {
			"fullname"	: "Tandridge Border Path",
			"name"		: "Tandridge Border",
			"attr"		: "ers",
			"dist_route"	: 52,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.231800,
			"longitude"	: -0.045319,
			"zoom"		: 11,
			"custom"	: ""
		},
		"tennyson.trail" : {
			"fullname"	: "Tennyson Trail",
			"name"		: "Tennyson Trail",
			"attr"		: "ers",
			"dist_route"	: 14,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.663000,
			"longitude"	: -1.428910,
			"zoom"		: 11,
			"custom"	: ""
		},
		"thames.estuary" : {
			"fullname"	: "Thames Estuary Trail",
			"name"		: "Thames Estuary",
			"attr"		: "ers",
			"dist_route"	: 115,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.480500,
			"longitude"	: 0.623474,
			"zoom"		: 10,
			"custom"	: ""
		},
		"thames.path" : {
			"fullname"	: "Thames Path - National Trail",
			"name"		: "Thames Path",
			"attr"		: "cehrstv",
			"dist_route"	: 185,
			"date_start"	: "2013-02-19",
			"date_end"	: "",
			"days_walked"	: 8,
			"days_camped"	: 6,
			"days_other"	: 0,
			"dist_walked"	: 144,
			"complete"	: 78,
			"latitude"	: 51.536100,
			"longitude"	: -0.999756,
			"zoom"		: 9,
			"custom"	: ""
		},
		"thanet.coast" : {
			"fullname"	: "Thanet Coastal Path",
			"name"		: "Thanet Coast",
			"attr"		: "cehrs",
			"dist_route"	: 21,
			"date_start"	: "2013-01-14",
			"date_end"	: "2013-01-15",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 21,
			"complete"	: 100,
			"latitude"	: 51.352100,
			"longitude"	: 1.332090,
			"zoom"		: 12,
			"custom"	: ""
		},
		"three.ridings" : {
			"fullname"	: "Three Ridings on Foot",
			"name"		: "Three Ridings",
			"attr"		: "ers",
			"dist_route"	: 444,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.985200,
			"longitude"	: -1.312870,
			"zoom"		: 8,
			"custom"	: ""
		},
		"three.towers" : {
			"fullname"	: "Three Towers",
			"name"		: "Three Towers",
			"attr"		: "ehrsx",
			"dist_route"	: 44,
			"date_start"	: "2010-04-10",
			"date_end"	: "2010-04-10",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 44,
			"complete"	: 100,
			"latitude"	: 51.510000,
			"longitude"	: -1.198200,
			"zoom"		: 11,
			"custom"	: "checkpoints"
		},
		"todmorden.centenary" : {
			"fullname"	: "Todmorden Centenary Way",
			"name"		: "Todmorden Centenary",
			"attr"		: "ers",
			"dist_route"	: 24,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.705900,
			"longitude"	: -2.097700,
			"zoom"		: 13,
			"custom"	: ""
		},
		"trans.pennine" : {
			"fullname"	: "Trans-Pennine Trail",
			"name"		: "Trans-Pennine",
			"attr"		: "ers",
			"dist_route"	: 209,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.589200,
			"longitude"	: -1.609500,
			"zoom"		: 8,
			"custom"	: ""
		},
		"tyne.estuary" : {
			"fullname"	: "Tyne Estuary to Source",
			"name"		: "Tyne Estuary",
			"attr"		: "ers",
			"dist_route"	: 87,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.901100,
			"longitude"	: -1.937710,
			"zoom"		: 10,
			"custom"	: ""
		},
		"wainwrights" : {
			"fullname"	: "Wainwrights - Lake District",
			"name"		: "Wainwrights",
			"attr"		: "AawchPps",
			"dist_route"	: 0,
			"date_start"	: "2012-10-22",
			"date_end"	: "",
			"days_walked"	: 7,
			"days_camped"	: 6,
			"days_other"	: 1,
			"dist_walked"	: 101,
			"complete"	: 11,
			"latitude"	: 54.484200,
			"longitude"	: -3.079490,
			"zoom"		: 10,
			"custom"	: ""
		},
		"wales.coast" : {
			"fullname"	: "Wales Coast Path",
			"name"		: "Wales Coast",
			"attr"		: "cefhrsx",
			"dist_route"	: 887,
			"date_start"	: "2013-07-08",
			"date_end"	: "2013-08-17",
			"days_walked"	: 41,
			"days_camped"	: 42,
			"days_other"	: 0,
			"dist_walked"	: 887,
			"complete"	: 100,
			"latitude"	: 52.442600,
			"longitude"	: -3.477170,
			"zoom"		: 8,
			"custom"	: "ferry_icon"
		},
		"wantsum.walk" : {
			"fullname"	: "Wantsum Walk",
			"name"		: "Wantsum Walk",
			"attr"		: "ers",
			"dist_route"	: 19,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 51.356300,
			"longitude"	: 1.214680,
			"zoom"		: 12,
			"custom"	: ""
		},
		"millennium.way" : {
			"fullname"	: "Way For The Millennium",
			"name"		: "Millennium Way",
			"attr"		: "ers",
			"dist_route"	: 38,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 52.762900,
			"longitude"	: -1.972050,
			"zoom"		: 10,
			"custom"	: ""
		},
		"welsh.3000s" : {
			"fullname"	: "Welsh 3000s",
			"name"		: "Welsh 3000s",
			"attr"		: "ersx",
			"dist_route"	: 24,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.133200,
			"longitude"	: -4.017910,
			"zoom"		: 12,
			"custom"	: "peaks"
		},
		"west.highland.way" : {
			"fullname"	: "West Highland Way - National Trail",
			"name"		: "West Highland Way",
			"attr"		: "ers",
			"dist_route"	: 94,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 56.328700,
			"longitude"	: -4.743350,
			"zoom"		: 9,
			"custom"	: ""
		},
		"west.somerset.coast" : {
			"fullname"	: "West Somerset Coast Path",
			"name"		: "West Somerset Coast",
			"attr"		: "cehrs",
			"dist_route"	: 28,
			"date_start"	: "2013-04-29",
			"date_end"	: "2013-04-30",
			"days_walked"	: 2,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 28,
			"complete"	: 100,
			"latitude"	: 51.172900,
			"longitude"	: -3.258820,
			"zoom"		: 11,
			"custom"	: ""
		},
		"west.sussex.literary" : {
			"fullname"	: "West Sussex Literary Trail",
			"name"		: "West Sussex Literary",
			"attr"		: "ers",
			"dist_route"	: 49,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 50.953700,
			"longitude"	: -0.526657,
			"zoom"		: 11,
			"custom"	: ""
		},
		"wey.navigations" : {
			"fullname"	: "Wey Navigations",
			"name"		: "Wey Navigations",
			"attr"		: "ehrstv",
			"dist_route"	: 20,
			"date_start"	: "2013-02-08",
			"date_end"	: "",
			"days_walked"	: 2,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 16,
			"complete"	: 82,
			"latitude"	: 51.282500,
			"longitude"	: -0.534897,
			"zoom"		: 11,
			"custom"	: ""
		},
		"white.cliffs" : {
			"fullname"	: "White Cliffs Country Trails",
			"name"		: "White Cliffs",
			"attr"		: "ehrs",
			"dist_route"	: 10,
			"date_start"	: "2013-01-14",
			"date_end"	: "2013-01-14",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 10,
			"complete"	: 100,
			"latitude"	: 51.174800,
			"longitude"	: 1.358530,
			"zoom"		: 12,
			"custom"	: ""
		},
		"wirral.circular" : {
			"fullname"	: "Wirral Circular Trail",
			"name"		: "Wirral Circular",
			"attr"		: "ers",
			"dist_route"	: 37,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.358300,
			"longitude"	: -3.059690,
			"zoom"		: 11,
			"custom"	: ""
		},
		"wysis.way" : {
			"fullname"	: "Wysis Way",
			"name"		: "Wysis Way",
			"attr"		: "ehrst",
			"dist_route"	: 52,
			"date_start"	: "2013-02-28",
			"date_end"	: "",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 7,
			"complete"	: 14,
			"latitude"	: 51.778900,
			"longitude"	: -2.395020,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.centurion" : {
			"fullname"	: "Yorkshire Dales Centurion Walk",
			"name"		: "Dales Centurion",
			"attr"		: "cehrst",
			"dist_route"	: 101,
			"date_start"	: "2011-08-03",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 0,
			"days_other"	: 1,
			"dist_walked"	: 25,
			"complete"	: 25,
			"latitude"	: 54.308500,
			"longitude"	: -2.234340,
			"zoom"		: 10,
			"custom"	: ""
		},
		"dales.challenge" : {
			"fullname"	: "Yorkshire Dales Challenge Walk",
			"name"		: "Dales Challenge",
			"attr"		: "ers",
			"dist_route"	: 22,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 54.178700,
			"longitude"	: -2.117270,
			"zoom"		: 12,
			"custom"	: ""
		},
		"dales.top.ten" : {
			"fullname"	: "Yorkshire Dales Top Ten",
			"name"		: "Dales Top Ten",
			"attr"		: "cehrst",
			"dist_route"	: 78,
			"date_start"	: "2010-09-25",
			"date_end"	: "",
			"days_walked"	: 3,
			"days_camped"	: 1,
			"days_other"	: 0,
			"dist_walked"	: 24,
			"complete"	: 31,
			"latitude"	: 54.265200,
			"longitude"	: -2.241210,
			"zoom"		: 10,
			"custom"	: ""
		},
		"yorkshire.three.peaks" : {
			"fullname"	: "Yorkshire Three Peaks",
			"name"		: "Yorkshire Three Peaks",
			"attr"		: "ehrsx",
			"dist_route"	: 24,
			"date_start"	: "2011-08-03",
			"date_end"	: "2011-08-03",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 24,
			"complete"	: 100,
			"latitude"	: 54.189000,
			"longitude"	: -2.333220,
			"zoom"		: 12,
			"custom"	: "peaks"
		},
		"yorkshire.wolds" : {
			"fullname"	: "Yorkshire Wolds Way - National Trail",
			"name"		: "Yorkshire Wolds Way",
			"attr"		: "ers",
			"dist_route"	: 79,
			"date_start"	: "",
			"date_end"	: "",
			"days_walked"	: 0,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 0,
			"complete"	: 0,
			"latitude"	: 53.963400,
			"longitude"	: -0.440826,
			"zoom"		: 10,
			"custom"	: ""
		},
		"join.4" : {
			"fullname"	: "Frampton on Severn",
			"name"		: "Frampton on Severn",
			"attr"		: "ehrs",
			"dist_route"	: 2,
			"date_start"	: "2013-08-25",
			"date_end"	: "2013-08-25",
			"days_walked"	: 1,
			"days_camped"	: 0,
			"days_other"	: 0,
			"dist_walked"	: 2,
			"complete"	: 100,
			"latitude"	: 51.782700,
			"longitude"	: -2.370300,
			"zoom"		: 12,
			"custom"	: ""
		},
	};
	return route_list;
}
